<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnitLite" Version="3.13.3" />
    <Compile Include="Program.cs" />
    <Compile Include="../../unity/MotionPlay/Assets/MotionPlay/Core/*.cs" />
    <Compile Include="../../unity/MotionPlay/Assets/MotionPlay/Tests/EditMode/ReceiverCoreTests.cs" />
  </ItemGroup>
</Project>
